"""Knowledge promotion and registry for the openMind continuous learning system.

When ambiguous experiences are resolved and training produces measurable weight
changes, the resulting learning is "promoted" into the KnowledgeRegistry as a
PromotedKnowledge entry.  Each entry carries metadata for spaced-repetition
review, domain indexing, and belief articulation so the system can later audit,
reinforce, revise, or deprecate what it has learned.
"""
from __future__ import annotations

import json
import logging
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------
# Data model
# -----------------------------------------------------------------------

@dataclass
class PromotedKnowledge:
    """A discrete piece of knowledge that the system has learned and promoted.

    Attributes:
        knowledge_id: Unique identifier for this knowledge entry.
        promoted_at: ISO-8601 UTC timestamp when the knowledge was promoted.
        training_cycle: Ordinal of the training cycle that produced this
            knowledge.
        source_domain: Domain tags from the experiences that gave rise to this
            knowledge.
        source_experience_ids: IDs of the experiences that contributed.
        layer_names: Names of the model layers whose weights changed
            significantly during the associated training step.
        promotion_scores: Dict of metric-name -> score captured at promotion
            time (e.g. reward improvement, loss delta).
        belief_summary: A natural-language articulation of what the model
            "believes" it learned, generated by the model itself.
        review_history: List of dicts recording each review event (timestamp,
            verdict, scores).
        last_reviewed: ISO-8601 timestamp of the most recent review, or None.
        review_count: How many review cycles have inspected this entry.
        status: Lifecycle state -- one of ``"active"``, ``"under_review"``,
            ``"deprecated"``, ``"revised"``, ``"reinforced"``.
        initial_confidence: Confidence score at promotion time, in [0.0, 1.0].
        current_confidence: Confidence score after the most recent review.
    """

    knowledge_id: str
    promoted_at: str
    training_cycle: int
    source_domain: List[str]
    source_experience_ids: List[str]
    layer_names: List[str]
    promotion_scores: Dict[str, float]
    belief_summary: str
    review_history: List[Dict[str, Any]] = field(default_factory=list)
    last_reviewed: Optional[str] = None
    review_count: int = 0
    status: str = "active"
    initial_confidence: float = 0.5
    current_confidence: float = 0.5

    # ---- validation ----

    _VALID_STATUSES = {
        "active", "under_review", "deprecated", "revised", "reinforced",
    }

    def __post_init__(self) -> None:
        if self.status not in self._VALID_STATUSES:
            raise ValueError(
                f"status must be one of {self._VALID_STATUSES}, "
                f"got {self.status!r}"
            )
        if not (0.0 <= self.initial_confidence <= 1.0):
            raise ValueError(
                f"initial_confidence must be in [0.0, 1.0], "
                f"got {self.initial_confidence}"
            )
        if not (0.0 <= self.current_confidence <= 1.0):
            raise ValueError(
                f"current_confidence must be in [0.0, 1.0], "
                f"got {self.current_confidence}"
            )

    # ---- computed properties ----

    @property
    def age_days(self) -> float:
        """Number of days since this knowledge was promoted."""
        promoted = datetime.fromisoformat(self.promoted_at)
        delta = datetime.now(timezone.utc) - promoted
        return delta.total_seconds() / 86_400

    @property
    def days_since_review(self) -> Optional[float]:
        """Number of days since the last review, or None if never reviewed."""
        if self.last_reviewed is None:
            return None
        reviewed = datetime.fromisoformat(self.last_reviewed)
        delta = datetime.now(timezone.utc) - reviewed
        return delta.total_seconds() / 86_400

    # ---- serialisation ----

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-serialisable dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> PromotedKnowledge:
        """Reconstruct from a dictionary."""
        return cls(**data)


# -----------------------------------------------------------------------
# Registry
# -----------------------------------------------------------------------

class KnowledgeRegistry:
    """Indexed store of promoted knowledge, persisted as JSONL.

    Maintains an in-memory ``domain_index`` mapping each domain tag to the
    list of :class:`PromotedKnowledge` IDs that belong to it, enabling fast
    domain-scoped lookups for review and contradiction scanning.

    Parameters:
        storage_path: Path to the backing JSONL file.
    """

    def __init__(self, storage_path: str | Path) -> None:
        self._path = Path(storage_path)
        self._path.parent.mkdir(parents=True, exist_ok=True)

        # In-memory indices -- rebuilt on first access
        self._entries: Dict[str, PromotedKnowledge] = {}
        self._domain_index: Dict[str, List[str]] = defaultdict(list)
        self._loaded = False

    # ---- lazy load -------------------------------------------------------

    def _ensure_loaded(self) -> None:
        """Populate caches from disk if not already done."""
        if self._loaded:
            return
        self._entries.clear()
        self._domain_index.clear()
        if self._path.exists():
            with open(self._path, "r", encoding="utf-8") as fh:
                for lineno, line in enumerate(fh, start=1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        pk = PromotedKnowledge.from_dict(data)
                        self._entries[pk.knowledge_id] = pk
                        for tag in pk.source_domain:
                            self._domain_index[tag].append(pk.knowledge_id)
                    except (json.JSONDecodeError, TypeError, ValueError) as exc:
                        logger.warning(
                            "Skipping corrupt knowledge entry at %s:%d -- %s",
                            self._path, lineno, exc,
                        )
        self._loaded = True

    # ---- public API ------------------------------------------------------

    def register_promotion(
        self,
        promotion_result: Dict[str, Any],
        model: Any,
        source_experiences: Sequence[Any],
    ) -> PromotedKnowledge:
        """Create and persist a new :class:`PromotedKnowledge` entry.

        Parameters:
            promotion_result: Dict containing training-cycle outputs such as
                ``layer_names``, ``promotion_scores``, ``training_cycle``, and
                ``confidence``.
            model: The current model wrapper (used to articulate the learning).
            source_experiences: The experiences that contributed to this
                promotion.

        Returns:
            The newly created :class:`PromotedKnowledge`.
        """
        self._ensure_loaded()

        knowledge_id = uuid.uuid4().hex
        now = datetime.now(timezone.utc).isoformat()
        domain_tags: List[str] = []
        experience_ids: List[str] = []
        for exp in source_experiences:
            experience_ids.append(exp.experience_id)
            for tag in getattr(exp, "domain_tags", []):
                if tag not in domain_tags:
                    domain_tags.append(tag)

        belief_summary = self._articulate_learning(
            model=model,
            source_experiences=source_experiences,
            promotion_scores=promotion_result.get("promotion_scores", {}),
        )

        confidence = float(promotion_result.get("confidence", 0.5))

        pk = PromotedKnowledge(
            knowledge_id=knowledge_id,
            promoted_at=now,
            training_cycle=int(promotion_result.get("training_cycle", 0)),
            source_domain=domain_tags,
            source_experience_ids=experience_ids,
            layer_names=list(promotion_result.get("layer_names", [])),
            promotion_scores=dict(promotion_result.get("promotion_scores", {})),
            belief_summary=belief_summary,
            initial_confidence=confidence,
            current_confidence=confidence,
        )

        # Persist
        with open(self._path, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(pk.to_dict()) + "\n")

        # Update caches
        self._entries[pk.knowledge_id] = pk
        for tag in pk.source_domain:
            self._domain_index[tag].append(pk.knowledge_id)

        logger.info(
            "Registered promoted knowledge %s (domains=%s, confidence=%.2f)",
            pk.knowledge_id, pk.source_domain, pk.current_confidence,
        )
        return pk

    def get(self, knowledge_id: str) -> Optional[PromotedKnowledge]:
        """Return a single entry by ID, or None."""
        self._ensure_loaded()
        return self._entries.get(knowledge_id)

    def get_by_domain(self, domain_tag: str) -> List[PromotedKnowledge]:
        """Return all promoted knowledge entries for a given domain tag."""
        self._ensure_loaded()
        ids = self._domain_index.get(domain_tag, [])
        return [self._entries[kid] for kid in ids if kid in self._entries]

    def get_active(self) -> List[PromotedKnowledge]:
        """Return all entries with ``status == "active"``."""
        self._ensure_loaded()
        return [pk for pk in self._entries.values() if pk.status == "active"]

    def get_review_candidates(self) -> List[PromotedKnowledge]:
        """Return knowledge entries that are due for spaced-repetition review.

        The base review interval follows an exponential schedule::

            interval_days = 7 * (2 ** review_count)

        This interval is **compressed** (shortened) by two factors:

        1. **Domain activity** -- if the domain has received new experiences
           recently, the knowledge should be reviewed sooner to check for
           drift or contradiction.
        2. **Peer revisions** -- if other knowledge in the same domain has
           recently been revised or deprecated, related entries should be
           reviewed sooner as a precaution.

        Returns:
            List of :class:`PromotedKnowledge` entries due for review, sorted
            by urgency (most overdue first).
        """
        self._ensure_loaded()
        now = datetime.now(timezone.utc)
        candidates: List[tuple[float, PromotedKnowledge]] = []

        # Pre-compute domain-level compression factors
        domain_compression = self._compute_domain_compression()

        for pk in self._entries.values():
            if pk.status in ("deprecated",):
                continue  # nothing to review

            base_interval = 7.0 * (2 ** pk.review_count)

            # Apply domain-activity compression
            compression = 1.0
            for tag in pk.source_domain:
                tag_compression = domain_compression.get(tag, 1.0)
                compression = min(compression, tag_compression)

            effective_interval = base_interval * compression

            # Determine when the next review is due
            if pk.last_reviewed is not None:
                last = datetime.fromisoformat(pk.last_reviewed)
            else:
                last = datetime.fromisoformat(pk.promoted_at)

            due_at = last + timedelta(days=effective_interval)
            if now >= due_at:
                overdue_days = (now - due_at).total_seconds() / 86_400
                candidates.append((overdue_days, pk))

        # Most overdue first
        candidates.sort(key=lambda pair: pair[0], reverse=True)
        return [pk for _, pk in candidates]

    def update(self, updated: PromotedKnowledge) -> None:
        """Persist an updated entry (full rewrite of the backing file)."""
        self._ensure_loaded()
        self._entries[updated.knowledge_id] = updated
        self._rewrite()
        logger.debug("Updated knowledge %s", updated.knowledge_id)

    def load_all(self) -> List[PromotedKnowledge]:
        """Return every knowledge entry."""
        self._ensure_loaded()
        return list(self._entries.values())

    @property
    def domain_index(self) -> Dict[str, List[str]]:
        """Expose the domain -> knowledge-id index (read-only view)."""
        self._ensure_loaded()
        return dict(self._domain_index)

    def __len__(self) -> int:
        self._ensure_loaded()
        return len(self._entries)

    # ---- internal helpers ------------------------------------------------

    def _articulate_learning(
        self,
        model: Any,
        source_experiences: Sequence[Any],
        promotion_scores: Dict[str, float],
    ) -> str:
        """Ask the model to articulate what it learned in natural language.

        Parameters:
            model: The current model wrapper.
            source_experiences: Experiences that contributed to this learning.
            promotion_scores: Metric scores captured at promotion time.

        Returns:
            A natural-language belief summary string.
        """
        # Build a representative sample of input/output pairs
        examples = []
        for exp in source_experiences[:5]:  # cap at 5 to keep prompt manageable
            examples.append(
                f"  Input: {getattr(exp, 'input_context', '?')}\n"
                f"  Output: {getattr(exp, 'output', '?')}\n"
                f"  Reward: {getattr(exp, 'reward_signal', '?')}"
            )
        examples_text = "\n---\n".join(examples)

        prompt = (
            "You are a reflective learning system.  Based on the following "
            "training experiences and their reward signals, articulate in one "
            "to three sentences what you have learned.  Focus on the *rule*, "
            "*pattern*, or *factual knowledge* that these experiences taught "
            "you, not on the experiences themselves.\n\n"
            f"Experiences:\n{examples_text}\n\n"
            f"Promotion scores: {json.dumps(promotion_scores)}\n\n"
            "Your articulation:"
        )

        # TODO: Send *prompt* to *model* and return the generated text.
        # Placeholder: return a generic summary until model integration is
        # wired up.
        logger.debug("_articulate_learning prompt length: %d chars", len(prompt))
        return (
            f"[Placeholder] Learning promoted from {len(source_experiences)} "
            f"experience(s) across domains "
            f"{[getattr(e, 'domain_tags', []) for e in source_experiences[:3]]}."
        )

    def _compute_domain_compression(self) -> Dict[str, float]:
        """Compute a compression factor for each domain tag.

        Compression makes review intervals shorter when:
        - The domain has many recently revised/deprecated peers (factor 0.5).
        - The domain is generally active (many entries, factor 0.7).

        Returns:
            Dict mapping domain tag -> compression multiplier in (0, 1].
            A value of 1.0 means no compression; lower = review sooner.
        """
        compression: Dict[str, float] = {}

        for tag, kid_list in self._domain_index.items():
            entries = [self._entries[k] for k in kid_list if k in self._entries]
            if not entries:
                compression[tag] = 1.0
                continue

            factor = 1.0

            # Peer-revision pressure: count recently revised/deprecated siblings
            recent_changes = sum(
                1 for e in entries
                if e.status in ("revised", "deprecated")
                and e.last_reviewed is not None
                and (datetime.now(timezone.utc)
                     - datetime.fromisoformat(e.last_reviewed)).days < 14
            )
            if recent_changes >= 2:
                factor = min(factor, 0.5)
            elif recent_changes == 1:
                factor = min(factor, 0.7)

            # Domain activity: more entries = more active domain
            if len(entries) > 10:
                factor = min(factor, 0.7)

            compression[tag] = factor

        return compression

    def _rewrite(self) -> None:
        """Overwrite the backing JSONL file from the in-memory cache."""
        with open(self._path, "w", encoding="utf-8") as fh:
            for pk in self._entries.values():
                fh.write(json.dumps(pk.to_dict()) + "\n")
